name: CI

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: main
  schedule:
    - cron:  '0 2 * * 2-6'

jobs:
  clone:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      with:
        path: ${{ github.workflow }}
        
    - uses: actions/checkout@v2
      with:
        repository: NetworkGradeLinux/mion
        token: ${{ secrets.ACCESS_TOKEN }}
        ref: dunfell
        fetch-depth: 0
        submodules: true
        path: ${{ github.workflow }}/mion
      
    - uses: actions/checkout@v2
      with:
        repository: NetworkGradeLinux/meta-mion
        token: ${{ secrets.ACCESS_TOKEN }}
        ref: dunfell
        path: ${{ github.workflow }}/mion/meta-mion
        
    - uses: actions/checkout@v2
      with:
        repository: NetworkGradeLinux/meta-mion-bsp
        token: ${{ secrets.ACCESS_TOKEN }}
        ref: dunfell
        path: ${{ github.workflow }}/mion/meta-mion-bsp
        
    - uses: actions/checkout@v2
      with:
        repository: NetworkGradeLinux/meta-mion-backports
        token: ${{ secrets.ACCESS_TOKEN }}
        ref: dunfell
        path: ${{ github.workflow }}/mion/meta-mion-backports

  build:
    runs-on: self-hosted
    needs: [clone]

    steps:
    - name: Pre-build steps
      shell: sh
      working-directory: ${{ github.workflow }}/mion/build/conf
      run: |
        echo "Event name: ${GITHUB_EVENT_NAME}"
        [ "${GITHUB_EVENT_NAME}" = "schedule" ] && rm -rf /home/gh-runner/sstate-cache/
        echo "DL_DIR ?= \"/srv/downloads/\"" >> local.conf
        echo "SSTATE_DIR ?= \"/home/gh-runner/sstate-cache/\"" >> local.conf
        mkdir /srv/DEPLOY/${GITHUB_RUN_NUMBER}_failed
        
    - name: Build QEMU
      shell: bash
      working-directory: ${{ github.workflow }}/mion
      run: |
        source openembedded-core/oe-init-build-env
        ../cronie.sh -m qemux86-64 -v qemu mion-image-onlpv1
        rsync -av tmp-glibc/deploy/images/qemux86-64/ /srv/DEPLOY/${GITHUB_RUN_NUMBER}_failed/qemux86-64-onlpv1

    - name: Build stordis-bf2556x-1t
      if: ${{ success() || failure() }}
      shell: bash
      working-directory: ${{ github.workflow }}/mion
      run: |
        source openembedded-core/oe-init-build-env
        ../cronie.sh -m stordis-bf2556x-1t mion-onie-image-onlpv1
        rsync -av tmp-glibc/deploy/images/stordis-bf2556x-1t/ /srv/DEPLOY/${GITHUB_RUN_NUMBER}_failed/stordis-bf2556x-1t_onie-onlpv1
        
    - name: Build stordis-bf6064x-t
      if: ${{ success() || failure() }}
      shell: bash
      working-directory: ${{ github.workflow }}/mion
      run: |
        source openembedded-core/oe-init-build-env
        ../cronie.sh -m stordis-bf6064x-t mion-onie-image-onlpv1
        rsync -av tmp-glibc/deploy/images/stordis-bf6064x-t/ /srv/DEPLOY/${GITHUB_RUN_NUMBER}_failed/stordis-bf6064x-t_onie-onlpv1

    - name: Build accton-wedge100bf-32x
      if: ${{ success() || failure() }}
      shell: bash
      working-directory: ${{ github.workflow }}/mion
      run: |
        source openembedded-core/oe-init-build-env
        ../cronie.sh -m accton-wedge100bf-32x mion-onie-image-onlpv1
        rsync -av tmp-glibc/deploy/images/accton-wedge100bf-32x/ /srv/DEPLOY/${GITHUB_RUN_NUMBER}_failed/accton-wedge100bf-32x_onie-onlpv1

    - name: Build accton-wedge100bf-65x
      if: ${{ success() || failure() }}
      shell: bash
      working-directory: ${{ github.workflow }}/mion
      run: |
        source openembedded-core/oe-init-build-env
        ../cronie.sh -m accton-wedge100bf-65x mion-onie-image-onlpv1
        rsync -av tmp-glibc/deploy/images/accton-wedge100bf-65x/ /srv/DEPLOY/${GITHUB_RUN_NUMBER}_failed/accton-wedge100bf-65x_onie-onlpv1

    - name: Build accton-asgvolt64
      if: ${{ success() || failure() }}
      shell: bash
      working-directory: ${{ github.workflow }}/mion
      run: |
        source openembedded-core/oe-init-build-env
        ../cronie.sh -m accton-asgvolt64 mion-onie-image-onlpv1
        rsync -av tmp-glibc/deploy/images/accton-asgvolt64/ /srv/DEPLOY/${GITHUB_RUN_NUMBER}_failed/accton-asgvolt64_onie-onlpv1
        
    - name: Build delta-tn48m
      if: ${{ success() || failure() }}
      shell: bash
      working-directory: ${{ github.workflow }}/mion
      run: |
        source openembedded-core/oe-init-build-env
        ../cronie.sh -m delta-tn48m mion-onie-image-dent-initramfs
        rsync -av tmp-glibc/deploy/images/delta-tn48m/ /srv/DEPLOY/${GITHUB_RUN_NUMBER}_failed/delta-tn48m_onie-image-dent-initramfs

    - name: Generate package feed
      if: ${{ success() && github.event_name == 'schedule' }}
      shell: bash
      working-directory: ${{ github.workflow }}/mion
      env: 
        PACKAGE_FEED: |
          stordis-bf2556x-1t
          stordis-bf6064x-t
          accton-wedge100bf-32x
          accton-wedge100bf-65x
          accton-asgvolt64
          delta-tn48m
      run: |
        RELEASE_DATE=$(awk '/^DISTRO_DATE/{print $3}' meta-mion/conf/distro/mion.conf | tr -d \")
        source openembedded-core/oe-init-build-env
        for sys in $PACKAGE_FEED; do ../cronie.sh -m "${sys}" package-index; done
        rsync -av tmp-glibc/deploy/ipk/ /srv/www/repo/${RELEASE_DATE}/

    - name: Post-build steps
      if: ${{ success() }}
      shell: sh
      run: |
        cd /srv/DEPLOY/
        mv ${GITHUB_RUN_NUMBER}_failed ${GITHUB_RUN_NUMBER}
        find ${GITHUB_RUN_NUMBER} -type f -size +4G -delete
        rm -rf $(ls -1t | tail -n +32)
        
    - name: Slack Notification on Fail
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: gh-notify
        SLACK_COLOR: danger
        SLACK_ICON: https://raw.githubusercontent.com/phil-r/slack-emoji/master/emojis/Memes/thisisfine.png
        SLACK_TITLE: Build Failure
        SLACK_MESSAGE: "Workflow: ${{ github.workflow }}  RunID: ${{ github.run_id }}"
        SLACK_USERNAME: Mion CI
        SLACK_MSG_AUTHOR: GitHub
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_FOOTER: ""
        MSG_MINIMAL: actions url
      
    - name: Slack Notification on Success
      if: ${{ success() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: gh-notify
        SLACK_COLOR: good
        SLACK_ICON: https://raw.githubusercontent.com/phil-r/slack-emoji/master/emojis/Memes/allthe.png
        SLACK_MESSAGE: "Workflow: ${{ github.workflow }}  RunID: ${{ github.run_id }}"
        SLACK_TITLE: Build Success
        SLACK_USERNAME: Mion CI
        SLACK_MSG_AUTHOR: GitHub
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_FOOTER: ""
        MSG_MINIMAL: actions url
