name: CI

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: main
  schedule:
    - cron:  '0 2 * * 2-6'

jobs:
  clone:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
        
    - uses: actions/checkout@v2
      with:
        repository: NetworkGradeLinux/mion
        token: 15778706457973f3e610979dca82f8854e766d66
        ref: dunfell
        fetch-depth: 0
        submodules: true
        path: mion
      
    - uses: actions/checkout@v2
      with:
        repository: NetworkGradeLinux/meta-mion
        token: 15778706457973f3e610979dca82f8854e766d66
        ref: dunfell
        path: mion/meta-mion
        
    - uses: actions/checkout@v2
      with:
        repository: NetworkGradeLinux/meta-mion-bsp
        token: 15778706457973f3e610979dca82f8854e766d66
        ref: dunfell
        path: mion/meta-mion-bsp  

  build:
    runs-on: self-hosted
    needs: [clone]

    steps:
    - name: Pre-build steps
      shell: sh
      working-directory: mion/build/conf
      run: |
        echo "DL_DIR ?= \"/home/gh-runner/downloads/\"" >> local.conf
        mkdir ~/DEPLOY/${GITHUB_RUN_NUMBER}_failed

    - name: Build QEMU
      shell: bash
      working-directory: mion
      run: |
        source openembedded-core/oe-init-build-env
        ../mc_build.sh -v qemu -m qemux86-64 -h host-onie:mion-image-onlpv1

    - name: Build stordis-bf2556x-1t (Mender+ONIE)
      if: ${{ success() || failure() }}
      shell: bash
      working-directory: mion
      run: |
        source openembedded-core/oe-init-build-env
        ../mc_build.sh -m stordis-bf2556x-1t -c guest:mion-guest-onlpv1 -h host-mender:mion-host
        rsync -av tmp-glibc/deploy/images/stordis-bf2556x-1t/ ~/DEPLOY/${GITHUB_RUN_NUMBER}_failed/stordis-bf2556x-1t_mender-onlpv1
        ../mc_build.sh -m stordis-bf2556x-1t -h host-onie:mion-onie-image-onlpv1
        rsync -av tmp-glibc/deploy/images/stordis-bf2556x-1t/ ~/DEPLOY/${GITHUB_RUN_NUMBER}_failed/stordis-bf2556x-1t_onie-onlpv1
        
    - name: Build stordis-bf6064x-t (Mender+ONIE)
      if: ${{ success() || failure() }}
      shell: bash
      working-directory: mion
      run: |
        source openembedded-core/oe-init-build-env
        ../mc_build.sh -m stordis-bf6064x-t -c guest:mion-guest-onlpv1 -h host-mender:mion-host
        rsync -av tmp-glibc/deploy/images/stordis-bf6064x-t/ ~/DEPLOY/${GITHUB_RUN_NUMBER}_failed/stordis-bf6064x-t_mender-onlpv1
        ../mc_build.sh -m stordis-bf6064x-t -h host-onie:mion-onie-image-onlpv1
        rsync -av tmp-glibc/deploy/images/stordis-bf6064x-t/ ~/DEPLOY/${GITHUB_RUN_NUMBER}_failed/stordis-bf6064x-t_onie-onlpv1

    - name: Build accton-wedge100bf-32x (ONIE)
      if: ${{ success() || failure() }}
      shell: bash
      working-directory: mion
      run: |
        source openembedded-core/oe-init-build-env
        ../mc_build.sh -m accton-wedge100bf-32x -h host-onie:mion-onie-image-onlpv1
        rsync -av tmp-glibc/deploy/images/accton-wedge100bf-32x/ ~/DEPLOY/${GITHUB_RUN_NUMBER}_failed/accton-wedge100bf-32x_onie-onlpv1

    - name: Build accton-wedge100bf-65x (ONIE)
      if: ${{ success() || failure() }}
      shell: bash
      working-directory: mion
      run: |
        source openembedded-core/oe-init-build-env
        ../mc_build.sh -m accton-wedge100bf-65x -h host-onie:mion-onie-image-onlpv1
        rsync -av tmp-glibc/deploy/images/accton-wedge100bf-65x/ ~/DEPLOY/${GITHUB_RUN_NUMBER}_failed/accton-wedge100bf-65x_onie-onlpv1

    - name: Build accton-asgvolt64 (ONIE)
      if: ${{ success() || failure() }}
      shell: bash
      working-directory: mion
      run: |
        source openembedded-core/oe-init-build-env
        ../mc_build.sh -m accton-asgvolt64 -h host-onie:mion-onie-image-onlpv1
        rsync -av tmp-glibc/deploy/images/accton-asgvolt64/ ~/DEPLOY/${GITHUB_RUN_NUMBER}_failed/accton-asgvolt64_onie-onlpv1
    
    - name: Post-build steps
      if: ${{ success() }}
      shell: sh
      run: |
        cd ~/DEPLOY/
        mv ${GITHUB_RUN_NUMBER}_failed ${GITHUB_RUN_NUMBER}
        find ${GITHUB_RUN_NUMBER} -type f -size +4G -delete
        rm -rf $(ls -1t | tail -n +12)
        
    - name: Slack Notification on Fail
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: gh-notify
        SLACK_COLOR: danger
        SLACK_ICON: https://raw.githubusercontent.com/phil-r/slack-emoji/master/emojis/Memes/thisisfine.png
        SLACK_TITLE: Build Failure
        SLACK_MESSAGE: "Workflow: ${{ github.workflow }}  RunID: ${{ github.run_id }}"
        SLACK_USERNAME: Mion CI
        SLACK_MSG_AUTHOR: GitHub
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_FOOTER: ""
        MSG_MINIMAL: actions url
      
    - name: Slack Notification on Success
      if: ${{ success() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: gh-notify
        SLACK_COLOR: good
        SLACK_ICON: https://raw.githubusercontent.com/phil-r/slack-emoji/master/emojis/Memes/allthe.png
        SLACK_MESSAGE: "Workflow: ${{ github.workflow }}  RunID: ${{ github.run_id }}"
        SLACK_TITLE: Build Success
        SLACK_USERNAME: Mion CI
        SLACK_MSG_AUTHOR: GitHub
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_FOOTER: ""
        MSG_MINIMAL: actions url
