name: CI

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: main
  schedule:
    - cron:  '0 2 * * 2-6'

jobs:
  clone:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
        
    - uses: actions/checkout@v2
      with:
        repository: NetworkGradeLinux/mion
        token: 15778706457973f3e610979dca82f8854e766d66
        ref: dunfell
        fetch-depth: 0
        submodules: true
        path: mion
      
    - uses: actions/checkout@v2
      with:
        repository: NetworkGradeLinux/meta-mion
        token: 15778706457973f3e610979dca82f8854e766d66
        ref: dunfell
        path: mion/meta-mion
        
    - uses: actions/checkout@v2
      with:
        repository: NetworkGradeLinux/meta-mion-bsp
        token: 15778706457973f3e610979dca82f8854e766d66
        ref: dunfell
        path: mion/meta-mion-bsp  
  
  build:
    runs-on: self-hosted
    needs: [clone]

    steps:
    - name: Set downloads dir
      shell: sh
      working-directory: mion/build/conf
      run: echo "DL_DIR ?= \"/home/gh-runner/downloads/\"" >> local.conf

    - name: Build stordis-bf2556x-1t Mender/ONLPv1
      shell: bash
      working-directory: mion
      run: |
        source openembedded-core/oe-init-build-env
        ../mc_build.sh -m stordis-bf2556x-1t -c guest:mion-guest-onlpv1 -h host-mender:mion-host
        rsync -av tmp-glibc/deploy/images/stordis-bf2556x-1t ${GITHUB_WORKSPACE}/stordis-bf2556x-1t_mender-onlpv1
    
    - name: Build accton-asgvolt64 Mender/ONLPv1
      shell: bash
      working-directory: mion
      run: |
        source openembedded-core/oe-init-build-env
        ../mc_build.sh -m accton-asgvolt64 -c guest:mion-guest-onlpv1 -h host-mender:mion-host
        rsync -av tmp-glibc/deploy/images/accton-asgvolt64 ${GITHUB_WORKSPACE}/accton-asgvolt64_mender-onlpv1
    
    - name: Remove Mender layer
      shell: sh
      working-directory: mion/build/conf
      run: sed -i '/meta-mender/d' bblayers.conf
  
    - name: Build stordis-bf2556x-1t ONIE/ONLPv1
      shell: bash
      working-directory: mion
      run: |
        source openembedded-core/oe-init-build-env
        sed -i '/meta-mender/d' conf/bblayers.conf
        ../mc_build.sh -m stordis-bf2556x-1t -h host-onie:mion-onie-image-onlpv1
        rsync -av tmp-glibc/deploy/images/stordis-bf2556x-1t ${GITHUB_WORKSPACE}/stordis-bf2556x-1t_onie-onlpv1

    - name: Build accton-asgvolt64 ONIE/ONLPv1
      shell: bash
      working-directory: mion
      run: |
        source openembedded-core/oe-init-build-env
        ../mc_build.sh -m accton-asgvolt64 -h host-onie:mion-onie-image-onlpv1
        rsync -av tmp-glibc/deploy/images/accton-asgvolt64 ${GITHUB_WORKSPACE}/accton-asgvolt64_onie-onlpv1
