name: CI

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 2 * * 2-6'

jobs:
  clone:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
        
    - uses: actions/checkout@v2
      with:
        repository: APS-Networks/mion
        token: 15778706457973f3e610979dca82f8854e766d66
        ref: dunfell
        fetch-depth: 0
        submodules: true
        path: mion
      
    - uses: actions/checkout@v2
      with:
        repository: APS-Networks/meta-mion
        token: 15778706457973f3e610979dca82f8854e766d66
        ref: dunfell
        path: mion/meta-mion
        
    - uses: actions/checkout@v2
      with:
        repository: APS-Networks/meta-mion-stordis
        token: 15778706457973f3e610979dca82f8854e766d66
        ref: dunfell
        path: mion/meta-mion-stordis  
  
  build:
    runs-on: self-hosted
    needs: [clone]

    steps:
    - name: Build Mender/ONLPv1
      shell: bash
      working-directory: mion
      run: |
        source openembedded-core/oe-init-build-env
        ../mc_build.sh -m stordis-bf2556x-1t -c guest:mion-guest-onlpv1,guest:mion-guest-onlpv2 -h host-mender:mion-host
        rsync -av tmp/deploy/images/stordis-bf2556x-1t ${GITHUB_WORKSPACE}/stordis-bf2556x-1t_mender-onlpv1
    
    - name: Remove Mender layer
      shell: sh
      working-directory: mion/build/conf
      run: sed -i '/meta-mender/d' bblayers.conf
  
    - name: Build Onie/ONLPv1
      shell: bash
      working-directory: mion
      run: |
        source openembedded-core/oe-init-build-env
        sed -i '/meta-mender/d' conf/bblayers.conf
        ../mc_build.sh -m stordis-bf2556x-1t -h host-onie:mion-onie-image-onlpv1
        rsync -av tmp/deploy/images/stordis-bf2556x-1t ${GITHUB_WORKSPACE}/stordis-bf2556x-1t_onie-onlpv1
    
    - name: Build Onie/ONLPv2
      shell: bash
      working-directory: mion
      run: |
        source openembedded-core/oe-init-build-env
        ../mc_build.sh -m stordis-bf2556x-1t -h host-onie:mion-onie-image-onlpv2
        rsync -av tmp/deploy/images/stordis-bf2556x-1t ${GITHUB_WORKSPACE}/stordis-bf2556x-1t_onie-onlpv2
